language: java
before_install:
  # Download gradle wrapper
  - wget -P ./gradle/wrapper "raw.githubusercontent.com/MinecraftForge/ForgeGradle/FG_2.3/gradle/wrapper/gradle-wrapper.jar"
  - wget -P ./gradle/wrapper "https://raw.githubusercontent.com/MinecraftForge/ForgeGradle/FG_2.3/gradle/wrapper/gradle-wrapper.properties"
  - wget "https://raw.githubusercontent.com/MinecraftForge/ForgeGradle/FG_2.3/gradlew"
  - chmod +x ./gradlew
  
install: ./gradlew setupCIWorkspace
script: ./gradlew build
notifications:
  email: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
